Make assignments to textArea.style.{top,left} strings.
While assigning a number works, it breaks the build when trying to compile this library with strict type checking enabled, giving the following error message:

ERROR: …/cbn-copy-clipboard-behavior_cbn-copy-clipboard-behavior_crisp.js:32 assignment to property top of CSSStyleDeclaration
found   : number
required: string
      textArea.style.top = 0;
      ^^^^^^^^^^^^^^^^^^^^^^